name: parsec
description: Multi-platform `parsec` plugin for Flutter to calculate math equations using C++ library. Supports android.
version: 0.1.0
repository: https://github.com/oxeanbits/parsec_flutter/tree/main/parsec

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  parsec_platform_interface: ^0.1.1
  parsec_android:
    path: ../parsec_android/
  parsec_linux:
    path: ../parsec_linux/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: parsec_android
      linux:
        default_package: parsec_linux
